### PR TITLE
fix(module_fallback): Catching recursive search if method doesnt exist

### LINKED ISSUE #613: 🐛 [Bug] Compiling a model containing ModuleList gives the error "Method 'forward' is not defined."
##  Bug Description

I get an error when trying to compile a model that contains a ModuleList.

```
terminate called after throwing an instance of 'c10::Error'
  what():  Method 'forward' is not defined.
```
First, I generated a TorchScript model as follows.

```python
#!/usr/bin/env python3
import torch.jit
import torch.nn as nn


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.convs = nn.ModuleList([nn.Conv2d(256, 256, 3, padding=1) for _ in range(100)])

    def forward(self, x):
        for c in self.convs:
            x = c.forward(x)
        return x


model = Net()
input_data = torch.empty([1, 256, 32, 32])
traced_model = torch.jit.trace(model, input_data)
traced_model.save("model.ts")
```

Then I tried to compile with TRTorch with the following code.

```cpp
#include <torch/script.h>
#include <trtorch/trtorch.h>
using namespace std;

int main() {
  constexpr int64_t INPUT_CHANNEL_NUM = 256;
  constexpr int64_t IMAGE_SIZE = 32;
  torch::jit::Module module = torch::jit::load("model.ts");
  module.to(torch::kCUDA);
  module.eval();

  std::vector<int64_t> in_sizes = {1, INPUT_CHANNEL_NUM, IMAGE_SIZE, IMAGE_SIZE};
  trtorch::CompileSpec::Input range(in_sizes);
  trtorch::CompileSpec info({range});
  module = trtorch::CompileGraph(module, info);
  cout << "finish" << endl;
}
```

When I try to compile and run the cpp code, I get the following error:

```
terminate called after throwing an instance of 'c10::Error'
  what():  Method 'forward' is not defined.
Exception raised from get_method at external/libtorch/include/torch/csrc/jit/api/object.h:103 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f500d73d1d9 in /root/libtorch/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd2 (0x7f500d739812 in /root/libtorch/libtorch/lib/libc10.so)
frame #2: trtorch::core::lowering::passes::NotateModuleForFallback(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) + 0x2e21 (0x7f500d69b6c1 in /root/trtorch-test/../trtorch/lib/libtrtorch.so)
frame #3: trtorch::core::lowering::passes::NotateModuleForFallback(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) + 0x1ae8 (0x7f500d69a388 in /root/trtorch-test/../trtorch/lib/libtrtorch.so)
frame #4: trtorch::core::lowering::LowerModule(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) + 0x112 (0x7f500d67e442 in /root/trtorch-test/../trtorch/lib/libtrtorch.so)
frame #5: trtorch::core::lowering::Lower(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, trtorch::core::lowering::LowerInfo const&) + 0x1822 (0x7f500d681a02 in /root/trtorch-test/../trtorch/lib/libtrtorch.so)
frame #6: trtorch::core::ConvertGraphToTRTEngine(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, trtorch::core::CompileSpec) + 0x7b (0x7f500d58267b in /root/trtorch-test/../trtorch/lib/libtrtorch.so)
frame #7: trtorch::core::CompileGraph(torch::jit::Module const&, trtorch::core::CompileSpec) + 0x26c (0x7f500d5871cc in /root/trtorch-test/../trtorch/lib/libtrtorch.so)
frame #8: trtorch::CompileGraph(torch::jit::Module const&, trtorch::CompileSpec) + 0x468 (0x7f500d576b48 in /root/trtorch-test/../trtorch/lib/libtrtorch.so)
frame #9: <unknown function> + 0x5b54 (0x563e0d351b54 in ./Test)
frame #10: <unknown function> + 0x5d93 (0x563e0d351d93 in ./Test)
frame #11: __libc_start_main + 0xf3 (0x7f4f17ee30b3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #12: <unknown function> + 0x578e (0x563e0d35178e in ./Test)

Aborted (core dumped)

```

As a result of backtrace using gdb, the following output was obtained.

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fd983322859 in __GI_abort () at abort.c:79
#2  0x00007fd9835a8911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fd9835b438c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fd9835b43f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fd9835b46a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fda78b7a83e in c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /root/libtorch/libtorch/lib/libc10.so
#7  0x00007fda78adc6c1 in trtorch::core::lowering::passes::NotateModuleForFallback(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) ()
   from /root/trtorch-test/../trtorch/lib/libtrtorch.so
#8  0x00007fda78adb388 in trtorch::core::lowering::passes::NotateModuleForFallback(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) ()
   from /root/trtorch-test/../trtorch/lib/libtrtorch.so
#9  0x00007fda78abf442 in trtorch::core::lowering::LowerModule(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) ()
   from /root/trtorch-test/../trtorch/lib/libtrtorch.so
#10 0x00007fda78ac2a02 in trtorch::core::lowering::Lower(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, trtorch::core::lowering::LowerInfo const&) () from /root/trtorch-test/../trtorch/lib/libtrtorch.so
#11 0x00007fda789c367b in trtorch::core::ConvertGraphToTRTEngine(torch::jit::Module const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, trtorch::core::CompileSpec)
    () from /root/trtorch-test/../trtorch/lib/libtrtorch.so
#12 0x00007fda789c81cc in trtorch::core::CompileGraph(torch::jit::Module const&, trtorch::core::CompileSpec) () from /root/trtorch-test/../trtorch/lib/libtrtorch.so
#13 0x00007fda789b7b48 in trtorch::CompileGraph(torch::jit::Module const&, trtorch::CompileSpec) ()
   from /root/trtorch-test/../trtorch/lib/libtrtorch.so
#14 0x000055e65c501b54 in compile(bool) ()
#15 0x000055e65c501d93 in main ()
```

## To Reproduce

I created a repository for error reproduction. 

https://github.com/SakodaShintaro/trtorch-test/tree/20210828_forward_is_not_defined

You can use Docker to reproduce the environment where errors occur. Dockerfile is also available.

```sh
# create Docker image and run container
wget https://raw.githubusercontent.com/SakodaShintaro/trtorch-test/20210828_forward_is_not_defined/docker/Dockerfile
docker build -t trtorch-test-image .
docker run --gpus all -it --name trtorch-test trtorch-test-image:latest bash

# in container
git clone https://github.com/SakodaShintaro/trtorch-test -b 20210828_forward_is_not_defined
cd trtorch-test
./download_libtorch.sh
python3 model.py
mkdir build && cd build
cmake ..
make
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/libtorch/libtorch/lib
cp ../model.ts .
./Test
```

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - TRTorch Version : 0.4.0
 - PyTorch Version : 1.10
 - CPU Architecture: x86_64
 - OS : Ubuntu
 - How you installed PyTorch : Docker
 - Build command you used (if compiling from source): get binary from Release
 - Python version:3.8.10
 - CUDA version:11.4
 - GPU models and configuration: 2080ti

### PR DESCRIPTION
**Pull request by narendasan**
# Description

There was an issue where the module fallback notation pass just assumes
methods exist. This should catch that. This might be something we may want to release as a patch 

Fixes #613, (potentially  #609, Also probably partially solves: #608)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: core/lowering/passes/module_fallback.cpp [hunk 1]
```diff
@@ -62,7 +62,9 @@ void NotateModuleForFallback(
   }
 
   for (const auto sub_mod : mod.named_children()) {
-    NotateModuleForFallback(sub_mod.value, sub_mod.name, method_name, forced_fallback_modules);
+    if (sub_mod.value.find_method(method_name)) {
```
Comment (ArvindSridhar) [inline core/lowering/passes/module_fallback.cpp:65]: Is there ever a case where we might pass in a name other than "forward" as the method name here? In that case, would the desired behavior be to only recurse through submodules with that specific method (and ignore others, and their children)?

Comment (narendasan) [reply core/lowering/passes/module_fallback.cpp:65]: What we really should be doing is finding the Method calls and using that to recurse vs all children probably

File: core/lowering/lowering.cpp [hunk 2]
```diff
@@ -60,10 +60,9 @@ void LowerGraph(std::shared_ptr<torch::jit::Graph>& g, LowerInfo lower_info) {
...
 }
 
-torch::jit::Module LowerModule(
-    const torch::jit::Module& mod,
-    std::string method_name,
-    std::unordered_set<std::string> forced_fallback_modules) {
+torch::jit::Module LowerModule(const torch::jit::Module& mod, std::string method_name, const LowerInfo& lower_info) {
+  std::unordered_set<std::string> forced_fallback_modules(
+      lower_info.forced_fallback_modules.begin(), lower_info.forced_fallback_modules.end());
   passes::NotateModuleForFallback(mod, "", method_name, forced_fallback_modules);
```
Comment (peri044) [inline core/lowering/lowering.cpp:66]: When the forced_fallback_modules is empty, we don't need to have this pass so we can disable it. This can prevent iterating through all the nodes in graph. Disabling this also fixed BERT issue but your other fix is necessary.

**Review by peri044 — CHANGES_REQUESTED** [review]
One minor change maybe when forced_fallback_modules is empty ? 
PR runs fine and BERT 1.9 graph passes

**Comment by isgursoy** [comment]
Yeah when can we expect to get this patch as v0.4.1?

**Comment by narendasan** [comment]
We are trying to get out a patch release in the next couple weeks. The issue is I think this WAR is probably not the correct solution. I am trying to determine if a formal solution could be implemented in a reasonable amount of time

**Review by peri044 — APPROVED** [review]
LGTM. Tests pass

**Comment by narendasan** [comment]
@peri044 can you also test with a network you know fails? Also try with module level fallback specifying a module that is not part of the module to be compiled

**Comment by peri044** [comment]
@narendasan Tested a network (DETR) which failed previously. Tried a module which is not a part of the graph. Works fine.
