### PR TITLE
Fix bug that when the dim is negative or bigger than one in selec…

### LINKED ISSUE #399: 🐛 [Bug] When the dim is negative or bigger than one in select.int(tensor, dim, index), the result is wrong.
##  Bug Description

When the dim is negative or bigger than one in select.int(tensor, dim, index), the result is wrong. 
A tensor x like at::randint(1,10,{4,4,4}) and the result's shape  of aten::select(x, 1, 0) should be {4, 4}, but got {4,1,4}.  

## To Reproduce

Add a unit test in test_select.cpp
```
TEST(Converters, ATenSelectIntDimIsOneConvertsCorrectly) {
  const auto graph = R"IR(
      graph(%0 : Tensor):
        %2 : int = prim::Constant[value=1]()
        %3 : int = prim::Constant[value=0]()
        %4 : Tensor = aten::select(%0, %2, %3)
        return (%4))IR";

  auto g = std::make_shared<torch::jit::Graph>();

  torch::jit::parseIR(graph, &*g);

  auto in = at::randint(1, 10, {4, 4, 4}, {at::kCUDA});

  auto jit_in = at::clone(in);
  auto params = trtorch::core::conversion::get_named_params(g->inputs(), {});
  auto jit_results = trtorch::tests::util::RunGraph(g, params, {jit_in});

  auto trt_in = at::clone(in);
  params = trtorch::core::conversion::get_named_params(g->inputs(), {});
  auto trt_results = trtorch::tests::util::RunGraphEngine(g, params, {trt_in});

  // In order to check whether shape match that we don't do reshape.
  // E.g. x = at::randint(1, 10, {4, 4, 4}, {at::kCUDA}), then aten::select(x, 1, 0). We should get a tensor y with
  // shape {4, 4} instead of a tensor with shape {4, 1, 4}.
  ASSERT_TRUE(trtorch::tests::util::almostEqual(jit_results[0], trt_results[0], 2e-6));
}
```

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by guoruoqian**
…t.int(tensor, dim, index), the result is wrong

Signed-off-by: Ruoqian Guo <ruoqiang@nvidia.com>

# Description

Fix bug that when the dim is negative or bigger than one in select.int(tensor, dim, index), the result is wrong. 
In brief, I replace the `unpadDims` function with `squeezeDims` function and support dim is negative. When the input of `unpadDims` is {2,1,3}, the result is {2, 1, 3}. But we expect to get {2,3}.

In addition, i use the linters to ensure that my code matches the style guidelines. The linters changed the entire file(`core/conversion/converters/impl/select.cpp`) . I only modified the `aten::select.int` part in select.cpp.
 
Fixes #399 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: core/conversion/converters/impl/select.cpp [hunk 1]
```diff
@@ -65,111 +65,116 @@ bool add_split(ConversionCtx* ctx, const torch::jit::Node* n, args& args, bool s
...
+               shuffle_layer->setReshapeDimensions(util::squeezeDims(gather_out->getDimensions(), axis));
+               shuffle_layer->setName(util::node_info(n).c_str());
+               auto shuffle_out = shuffle_layer->getOutput(0);
+
+               auto out = ctx->AssociateValueAndTensor(n->outputs()[0], shuffle_out);
+
+               LOG_DEBUG("Output tensor shape: " << out->getDimensions());
+
+               return true;
+             }})
```
Comment (guoruoqian) [inline core/conversion/converters/impl/select.cpp:104]: I only modified this part to fix bug. Other parts of the code changed by linters.

**Review by narendasan — APPROVED** [review]
lgtm
