### PR TITLE
Verify zeros evaluator works correctly and detect programs that will have an empty TensorRT engine

### LINKED ISSUE #343: 🐛 [Bug] Encountered bug when using TRTorch
##  Bug Description

It seems that aten::zeros has bug.

## To Reproduce

1. make torchscript model
``` python
import torch
import torch.nn as nn

class TorchZeros(nn.Module):
    def __init__(self):
        super(TorchZeros, self).__init__()
    def forward(self, x):
        z = torch.zeros(x.shape)
        return z
    
input = torch.randn((1, 3, 224, 224))
model = TorchZeros()
model = torch.jit.script(model)

torch.jit.save(model, 'zeros.pt')
```

2. load model using c++ with libtorch and TRTorch
```cpp
#include <iostream>
#include <torch/torch.h>
#include <torch/script.h>

#include "trtorch/trtorch.h"

int main()
{
  torch::jit::script::Module model;
  model = torch::jit::load("./zeros.pt");
  std::cout << "model is loaded!" << std::endl;
  
  model.eval();
  std::vector<torch::jit::IValue> input_ivalue_tensor = {torch::randn({1, 3, 224, 224})};
  auto output = model.forward(input_ivalue_tensor).toTensor();
  std::cout << "output.sizes(): "<< output.sizes() << std::endl;

  model.to(torch::kCUDA);
  
  auto in = torch::randn({1, 3, 224, 224}, {torch::kCUDA});
  auto input_sizes = std::vector<trtorch::CompileSpec::InputRange>({in.sizes()});
  trtorch::CompileSpec info(input_sizes);
  
  auto trt_mod = trtorch::CompileGraph(model, info);

  return 0;
}
```

3. run 

Printed result
```
model is loaded!
output.sizes(): [1, 3, 224, 224]
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Aborted (core dumped)
```

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by narendasan**
# Description

This PR fixes the `aten::zeros` evaluator and adds a test to make sure it matches PyTorch execution. 
It also adds a check to see if a graph will result in a TensorRT engine that does nothing at runtime and errors out if so. 

Fixes #343 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: core/conversion/evaluators/aten.cpp [hunk 1]
```diff
@@ -118,10 +118,11 @@ auto aten_registrations TRTORCH_UNUSED =
                     // aten::zeros(int[] size, *, int? dtype=None, int? layout=None,
                     // Device? device=None, bool? pin_memory=None) -> (Tensor)
                     [](const torch::jit::Node* n, kwargs& args) -> c10::optional<torch::jit::IValue> {
-                      auto options = torch::TensorOptions()
-                                         .dtype(c10::ScalarType(args.at(n->output(1)).unwrapToInt()))
-                                         .layout(torch::kStrided)
-                                         .device(torch::kCUDA);
+                      auto options = torch::TensorOptions().layout(torch::kStrided).device(torch::kCUDA);
+
+                      if (!args.at(n->input(1)).isNone() && !args.at(n->input(1)).IValue()->isNone()) {
```
Comment (peri044) [inline core/conversion/evaluators/aten.cpp:123]: what is n->input(1) ? I can't seem to find any doc on it. Any comment here can help clarify this code snippet.

**Review by peri044 — APPROVED** [review]
Added a comment. Code LGTM
