### PR TITLE
Adding the new device API, fixing the a nested dict issue in the existing compile phase, adding new lowering pass for bn

### LINKED ISSUE #286: 🐛 [Bug] An wrong function call for `torch._C._jit_to_tensorrt` on `spec` in tutorial code.
##  Bug Description

This is a bug in a tutorial below.

* Web: https://nvidia.github.io/TRTorch/tutorials/use_from_pytorch.html
* Original ReST doc: https://github.com/NVIDIA/TRTorch/blob/51a2043217a3f6c93f393169961750733c0d26ec/docsrc/tutorials/use_from_pytorch.rst

To compile a model, `torch._C._jit_to_tensorrt()` is called with two parameters, `script_model._c` and `spec`.
But, a following error happened.

```
Traceback (most recent call last):
  File "simple.py", line 34, in <module>
    main()
  File "simple.py", line 27, in main
    trt_model = torch._C._jit_to_tensorrt(script_model._c, spec)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<string>", line 6, in __setstate__
                self.__processed_module = state[1]
                self.__create_backend()
                self.__handles = self.__backend.compile(self.__processed_module, self.__method_compile_spec)
                                 ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

RuntimeError: isGenericDict() INTERNAL ASSERT FAILED at "/opt/python/cp36-cp36m/lib/python3.6/site-packages/torch/include/ATen/core/ivalue_inl.h":830, please report a bug to PyTorch. Expected GenericDict but got Object
```

This error looks like caused by wrong parameter. In test code (https://github.com/NVIDIA/TRTorch/blob/b93627ecc7bb7123d2e32aff9d762dd0e6bc3166/tests/py/test_to_backend_api.py), this API is called with a different parameter like below. It looks like making additional `dict` with `forward` key is necessary.

```
trt_model = torch._C._jit_to_tensorrt(script_model._c, {'forward': spec})
```

## To Reproduce

1. Launch NGC TRT container, `nvcr.io/nvidia/tensorrt:20.03-py3`.
1. Install required libraries
    - `pip install https://github.com/NVIDIA/TRTorch/releases/download/v0.1.0/trtorch-0.1.0-cp36-cp36m-linux_x86_64.whl torchvision==0.7.0`
1. Run each step described in the tutorial.

My repro code is below. Note that I modified the tutorial code to use FP32 for test.

```
import torch
import trtorch
import torchvision.models as models

def main():
    model = models.mobilenet_v2(pretrained=True)
    script_model = torch.jit.script(model)

    spec = {
        "forward": trtorch.TensorRTCompileSpec({
            "input_shapes": [[1, 3, 300, 300]],
            "op_precision": torch.float32,
            "refit": False,
            "debug": False,
            "strict_types": False,
            "allow_gpu_fallback": True,
            "device_type": "gpu",
            "capability": trtorch.EngineCapability.default,
            "num_min_timing_iters": 2,
            "num_avg_timing_iters": 1,
            "max_batch_size": 0,
        })
    }
    # trt_model = torch._C._jit_to_tensorrt(script_model._c, {'forward': spec})
    trt_model = torch._C._jit_to_tensorrt(script_model._c, spec)

    x = torch.randn((1, 3, 300, 300)).to('cuda').to(torch.float32)
    print(trt_model.forward(x))


if __name__ == '__main__':
    main()
```

## Expected behavior

No exception.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.6.0
 - CPU Architecture: Intel(R) Core(TM) i7-6850K
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS (host) / Ubuntu 18.04.4 LTS (container)
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): N/A
 - Are you using local sources or building from archives: N/A
 - Python version: 3.6.9
 - CUDA version: 10.2.89
 - GPU models and configuration: TitanX (Pascal)
 - Any other relevant information: N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by narendasan**
# Description

This PR adds a new device sub struct to the `CompileSpec` structure reflecting the new DLA changes. 
It also addresses a nested dictionary issue in the compile phase of the backend api. 
Finally adds a lowering pass that addresses new dimension checks for the batchnorm operator.

This PR also bumps bazel and TensorRT versions in preparation for the next release. 

Fixes #286 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [X] My code follows the style guidelines of this project (You can use the linters)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas and hacks
- [X] I have made corresponding changes to the documentation
- [X] I have added tests to verify my fix or my feature
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: py/trtorch/csrc/tensorrt_classes.h [hunk 1]
```diff
@@ -17,6 +17,16 @@ namespace pyapi {
     return field_name;                      \
   }
 
+// TODO: Make this error message more informative
```
Comment (andi4191) [inline py/trtorch/csrc/tensorrt_classes.h:20]: Are we planning to address this later?

File: py/trtorch/csrc/tensorrt_classes.h [hunk 2]
```diff
@@ -59,7 +69,7 @@ struct Device : torch::CustomClassHolder {
         allow_gpu_fallback(false) // allow_gpu_fallback
   {}
 
-  ADD_FIELD_GET_SET(device_type, DeviceType);
+  ADD_ENUM_GET_SET(device_type, DeviceType, 1);
```
Comment (andi4191) [inline py/trtorch/csrc/tensorrt_classes.h:72]: What is "1" here?
Can we use enumeration?

File: py/trtorch/csrc/tensorrt_classes.h [hunk 3]
```diff
@@ -77,28 +87,22 @@ enum class EngineCapability : int8_t {
...
+  void setDeviceIntrusive(const c10::intrusive_ptr<Device>& d) {
+    device = *d;
+  }
+
+  ADD_ENUM_GET_SET(op_precision, DataType, 2);
   ADD_FIELD_GET_SET(refit, bool);
   ADD_FIELD_GET_SET(debug, bool);
   ADD_FIELD_GET_SET(strict_types, bool);
-  ADD_ENUM_GET_SET(capability, EngineCapability, 3);
+  ADD_ENUM_GET_SET(capability, EngineCapability, 2);
```
Comment (andi4191) [inline py/trtorch/csrc/tensorrt_classes.h:105]: How about using enumerations instead of hardcoded numbers?

**Review by andi4191 — CHANGES_REQUESTED** [review]
It seems to be a combination of 3 PRs
a) TensorRT and bazel version bumps
b) Batch normalization dimension check changes
c) Device struct changes

I would have recommend splitting the Batch normalization changes from this PR.

**Comment by narendasan** [comment]
The batchnorm and device checks are both in service of fixing to_backend so I think they are related. Like you couldnt use the to_backend api without both of these changes together so I think its alright that they are in the same PR. The version bump is minor, so i am not sure if its a big enough deal to review separately.

File: py/trtorch/csrc/tensorrt_classes.h (hunk 2 above)
Comment (narendasan) [reply py/trtorch/csrc/tensorrt_classes.h:72]: This macro creates a getter and setter pair that returns integers so that the function is torchbind compatible. the 1 is the max allowable value so that you dont get invalid ones.

File: py/trtorch/csrc/tensorrt_classes.h (hunk 3 above)
Comment (narendasan) [reply py/trtorch/csrc/tensorrt_classes.h:105]: We could do like a static cast to int of the enums, sounds like a good idea

File: tests/py/test_to_backend_api.py [hunk 4]
```diff
@@ -19,8 +19,11 @@ def setUp(self):
                     "refit": False,
                     "debug": False,
                     "strict_types": False,
-                    "allow_gpu_fallback": True,
-                    "device_type": "gpu",
+                    "device": {
```
Comment (narendasan) [inline tests/py/test_to_backend_api.py:22]: @andi4191 This struct looks correct to you right?

Comment (andi4191) [reply tests/py/test_to_backend_api.py:22]: I think you are missing dla_core?

File: py/trtorch/csrc/tensorrt_classes.h (hunk 1 above)
Comment (narendasan) [reply py/trtorch/csrc/tensorrt_classes.h:20]: Yeah, will need to think about it a bit more but shouldnt block this PR

**Review by andi4191 — APPROVED** [review]
LGTM
