### PR TITLE
Fix bug in squeeze

### LINKED ISSUE #392: 🐛 [Bug] Fix bug in squeeze converter
##  Bug Description

Some tensor like at::randint(1,10,{2,3,3}) dont need to squeeze and in squeeze converter there is no conditional judgment to handle it. In the PyTorch, when a tensor does not need to squeeze, it will return the tensor value directly.

## To Reproduce

Add a unit test in test_squeeze.cpp
```
TEST(Converters, ATenSqueezeDontNeedSqueezeConvertsCorrectly) {
  const auto graph = R"IR(
      graph(%0 : Tensor):
        %1 : int = prim::Constant[value=1]()
        %2 : Tensor = aten::squeeze(%0, %1)
        return (%2))IR";

  auto g = std::make_shared<torch::jit::Graph>();
  torch::jit::parseIR(graph, &*g);

  auto in = at::randint(1, 10, {2, 3, 3}, {at::kCUDA});

  auto params = trtorch::core::conversion::get_named_params(g->inputs(), {});
  auto jit_results = trtorch::tests::util::RunGraph(g, params, {in});

  params = trtorch::core::conversion::get_named_params(g->inputs(), {});
  auto trt_results = trtorch::tests::util::RunGraphEngine(g, params, {in});

  ASSERT_TRUE(trtorch::tests::util::almostEqual(jit_results[0], trt_results[0].reshape_as(jit_results[0]), 2e-6));
}
```
I got this error :
image

## Expected behavior
image

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): '1.7.1+cu110'
 - CPU Architecture: 
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): 
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:  3.7.6
 - CUDA version: cuda11.0
 - GPU models and configuration:
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by guoruoqian**
…a judgment condition to handle this situation

Signed-off-by: Ruoqian Guo <ruoqiang@nvidia.com>

# Description

Some tensor like at::randint(1,10,{2,3,3}) dont need to squeeze and add a judgment condition to handle this situation. 

Fixes #392 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: core/conversion/converters/impl/squeeze.cpp [hunk 1]
```diff
@@ -25,6 +25,15 @@ auto squeeze_registrations TRTORCH_UNUSED = RegisterNodeConversionPatterns().pat
          dim = selfDim.size() + dim;
        }
 
+       if (selfDim[dim] != 1) {
+         auto identity = ctx->net->addIdentity(*self);
```
Comment (narendasan) [inline core/conversion/converters/impl/squeeze.cpp:29]: Instead of the identity layer if we arent going to do anything we could just reassoicate the input ITensor with the output node

Comment (guoruoqian) [reply core/conversion/converters/impl/squeeze.cpp]: Yes，i remove the identity layer and reassoicate the input ITensor with the output node when we arent going to do anything. Thanks.

**Review by narendasan — APPROVED** [review]
LGTM
